spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: jetbra
  default-assignee-name: jetbra
  default-expiry-date: 2026-08-16